# Generated by Django 2.2.5 on 2022-01-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Score_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr1', models.FloatField(default=None)),
                ('pr2', models.FloatField(default=None)),
                ('A1', models.FloatField(default=None)),
                ('B1', models.FloatField(default=None)),
                ('C1', models.FloatField(default=None)),
                ('D1', models.FloatField(default=None)),
                ('A2', models.FloatField(default=None)),
                ('B2', models.FloatField(default=None)),
                ('C2', models.FloatField(default=None)),
                ('D2', models.FloatField(default=None)),
                ('E2', models.FloatField(default=None)),
                ('A3', models.FloatField(default=None)),
                ('B3', models.FloatField(default=None)),
                ('C3', models.FloatField(default=None)),
                ('D3', models.FloatField(default=None)),
                ('E3', models.FloatField(default=None)),
            ],
        ),
    ]
